name: Python Flash CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install flask pytest

      - name: Run tests
        run: pytest tests

  docker:
    runs-on: ubuntu-latest
    needs: test   # run docker build only if tests pass
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t flask-app .

      - name: Run container (detached)
        run: docker run -d -p 5000:5000 --name flask-container flask-app

      - name: Check if app is running
        run: |
          sleep 5
          curl http://127.0.0.1:5000/hello